#!/usr/bin/env python3
"""
Docusaurus Documentation Site Initializer

Creates a Docusaurus documentation site structure.
Executes via MCP code execution pattern - minimal tokens in context.
"""

import os
import sys
from pathlib import Path


PACKAGE_JSON_TEMPLATE = '''{{
  "name": "{site_name}",
  "version": "1.0.0",
  "private": true,
  "scripts": {{
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids"
  }},
  "dependencies": {{
    "@docusaurus/core": "^3.1.0",
    "@docusaurus/preset-classic": "^3.1.0",
    "@mdx-js/react": "^3.0.0",
    "clsx": "^2.0.0",
    "prism-react-renderer": "^2.3.0",
    "react": "^18.0.0",
    "react-dom": "^18.0.0"
  }},
  "devDependencies": {{
    "@docusaurus/module-type-aliases": "^3.1.0",
    "@docusaurus/types": "^3.1.0"
  }},
  "browserslist": {{
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 3 chrome version",
      "last 3 firefox version",
      "last 5 safari version"
    ]
  }},
  "engines": {{
    "node": ">=18.0"
  }}
}}
'''

DOCUSAURUS_CONFIG_TEMPLATE = '''// @ts-check
// Note: type annotations allow type checking and IDEs autocompletion

const lightCodeTheme = require('prism-react-renderer').themes.github;
const darkCodeTheme = require('prism-react-renderer').themes.dracula;

/** @type {{import('@docusaurus/types').Config}} */
const config = {{
  title: '{site_title}',
  tagline: 'AI-Powered Python Tutoring Platform',
  favicon: 'img/favicon.ico',

  // Set the production url of your site here
  url: 'https://your-org.github.io',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/{site_name}/',

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'your-org', // Usually your GitHub org/user name.
  projectName: '{site_name}', // Usually your repo name.

  onBrokenLinks: 'throw',
  onBrokenMarkdownLinks: 'warn',

  // Even if you don't use internalization, you can use this field to set useful
  // metadata like html lang. For example, if your site is Chinese, you may want
  // to replace "en" with "zh-Hans".
  i18n: {{
    defaultLocale: 'en',
    locales: ['en'],
  }},

  presets: [
    [
      'classic',
      /** @type {{import('@docusaurus/preset-classic').Options}} */
      ({{
        docs: {{
          sidebarPath: require.resolve('./sidebars.js'),
          editUrl:
            'https://github.com/your-org/{site_name}/tree/main/',
        }},
        theme: {{
          customCss: require.resolve('./src/css/custom.css'),
        }},
      }}),
    ],
  ],

  themeConfig:
    /** @type {{import('@docusaurus/preset-classic').ThemeConfig}} */
    ({{
      // Replace with your project's social card
      image: 'img/docusaurus-social-card.jpg',
      navbar: {{
        title: '{site_title}',
        items: [
          {{
            type: 'docSidebar',
            sidebarId: 'tutorialSidebar',
            position: 'left',
            label: 'Tutorial',
          }},
          {{
            href: 'https://github.com/your-org/{site_name}',
            label: 'GitHub',
            position: 'right',
          }},
        ],
      }},
      footer: {{
        style: 'dark',
        links: [
          {{
            title: 'Docs',
            items: [
              {{
                label: 'Tutorial',
                to: '/docs/intro',
              }},
            ],
          }},
        ],
        copyright: `Copyright © ${{new Date().getFullYear()}} {site_title}. Built with Docusaurus.`,
      }},
      prism: {{
        theme: lightCodeTheme,
        darkTheme: darkCodeTheme,
      }},
    }}),
}};

module.exports = config;
'''

SIDEBARS_TEMPLATE = '''// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {{
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{{type: 'autogenerated', dirName: '.'}}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {{
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    }},
  ],
   */
}};

module.exports = sidebars;
'''

INTRO_DOC_TEMPLATE = '''---
sidebar_position: 1
---

# Introduction

Welcome to the **{site_title}** documentation\!

## Overview

This documentation covers the LearnFlow platform, an AI-powered Python tutoring system.

## Quick Start

```bash
# Start the development server
npm run start

# Build for production
npm run build

# Deploy to GitHub Pages
npm run deploy
```

## Key Features

- 🤖 AI-powered tutoring agents
- 📝 Interactive code exercises
- 📊 Progress tracking and analytics
- 🎯 Personalized learning paths

## Documentation Sections

- **Architecture**: System design and components
- **Skills**: AI agent skills documentation
- **Deployment**: Kubernetes and local development
- **API**: REST API reference

## Getting Help

- [GitHub Issues](https://github.com/your-org/{site_name}/issues)
- [Discussions](https://github.com/your-org/{site_name}/discussions)
'''

CUSTOM_CSS_TEMPLATE = '''/**
 * Any CSS included here will be global. The classic template
 * bundles Infima by default. Infima is a CSS framework designed to
 * work well for content-centric websites.
 */

/* You can override the default Infima variables here. */
:root {{
  --ifm-color-primary: #2e8555;
  --ifm-color-primary-dark: #29784c;
  --ifm-color-primary-darker: #277148;
  --ifm-color-primary-darkest: #205d3b;
  --ifm-color-primary-light: #33925d;
  --ifm-color-primary-lighter: #359962;
  --ifm-color-primary-lightest: #3cad6e;
  --ifm-code-font-size: 95%;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.1);
}}

/* For readability concerns, you should choose a lighter palette in dark mode. */
[data-theme='dark'] {{
  --ifm-color-primary: #25c2a0;
  --ifm-color-primary-dark: #21af90;
  --ifm-color-primary-darker: #1fa588;
  --ifm-color-primary-darkest: #1a8870;
  --ifm-color-primary-light: #29d5b0;
  --ifm-color-primary-lighter: #32d8b4;
  --ifm-color-primary-lightest: #4fddbf;
  --docusaurus-highlighted-code-line-bg: rgba(0, 0, 0, 0.3);
}}
'''

GITIGNORE_TEMPLATE = '''# Dependencies
node_modules/

# Build output
build/
.docusaurus/

# Environment variables
.env
.env.local

# IDE
.idea/
.vscode/
*.swp
*.swo

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Testing
coverage/
'''


def init_docusaurus_site(site_path: str) -> bool:
    """Initialize a Docusaurus documentation site."""
    
    site_dir = Path(site_path)
    site_name = site_dir.name.lower().replace("_", "-")
    site_title = site_dir.name.replace("_", " ").title()
    
    print(f"📁 Initializing Docusaurus site: {site_name}")
    print(f"📂 Location: {site_dir}")
    
    # Create directory structure
    dirs = [
        site_dir,
        site_dir / "docs",
        site_dir / "src" / "css",
        site_dir / "static" / "img",
    ]
    
    for dir_path in dirs:
        dir_path.mkdir(parents=True, exist_ok=True)
    
    # Create files
    files = {
        "package.json": PACKAGE_JSON_TEMPLATE.format(site_name=site_name),
        "docusaurus.config.js": DOCUSAURUS_CONFIG_TEMPLATE.format(
            site_name=site_name,
            site_title=site_title
        ),
        "sidebars.js": SIDEBARS_TEMPLATE,
        "docs/intro.md": INTRO_DOC_TEMPLATE.format(
            site_name=site_name,
            site_title=site_title
        ),
        "src/css/custom.css": CUSTOM_CSS_TEMPLATE,
        ".gitignore": GITIGNORE_TEMPLATE,
    }
    
    for filename, content in files.items():
        file_path = site_dir / filename
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"  ✓ Created {filename}")
    
    print(f"\n✓ Docusaurus site '{site_name}' initialized successfully")
    print(f"\n📝 Next steps:")
    print(f"  1. cd {site_path}")
    print(f"  2. npm install")
    print(f"  3. npm run start")
    print(f"  4. Add documentation to docs/ folder")
    
    return True


def main():
    """Main entry point."""
    if len(sys.argv) < 2:
        print("Usage: python init-docs.py <site-path>")
        print("\nExamples:")
        print("  python init-docs.py ./docs")
        print("  python init-docs.py ./learnflow-docs")
        sys.exit(1)
    
    site_path = sys.argv[1]
    success = init_docusaurus_site(site_path)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
